version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "fredrikhr"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "fredrikhr"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "fredrikhr"
