version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "fredrikhr"
  - package-ecosystem: "npm"
    directory: "/dotnet-nuget-push"
    schedule:
      interval: "daily"
    reviewers:
      - "fredrikhr"
  - package-ecosystem: "npm"
    directory: "/dotnet-sdk"
    schedule:
      interval: "daily"
    reviewers:
      - "fredrikhr"
