name: 'Prepare TH-NETII custom GitHub action'
description: 'Prepares a custom GitHub Actions action that uses typescript and the node enginge for execution.'
inputs:
  action-name:
    description: |
      The name of the action to prepare. Must be a folder name which is a
      sibling to the directory containing this prepare action.
    required: true
runs:
  using: composite
  steps:
    - shell: pwsh
      run: |
        Write-Host "::group::npm install $(Get-Location)"
        npm install
        Write-Host "::endgroup::"
      working-directory: ${{ github.action_path }}/../${{ inputs.action-name }}
    - shell: pwsh
      run: |
        Write-Host "::group::tsc $(Resolve-Path action.ts)"
        npx tsc action.ts
        Write-Host "::endgroup::"
      working-directory: ${{ github.action_path }}/../${{ inputs.action-name }}
author: Fredrik Høisæther Rasch <fredrik.rasch@gmail.com>
branding:
  color: purple
  icon: clipboard
