name: .NET Continuous Integration Release

on:
  workflow_run:
    workflows:
      - .NET Continuous Integration
    types:
      - completed
    branches:
      - main
      - releases/**

jobs:
  nupkg:
    name: Publish NuGet package
    runs-on: ubuntu-latest
    steps:
      - name: Prepare .NET NuGet Push action
        uses: ./def/typescript-action-prepare
        with:
          action-name: dotnet-nuget-push
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: ${{ github.event.workflow_run.repository.owner.login }}-${{ github.event.workflow_run.repository.name }}-nupkg-release
          repo: ${{ github.repository }}
      - name: dotnet nuget push
        uses: ./def/dotnet-nuget-push
