name: .NET Core Continuous Integration
on:
  pull_request: {}
  push:
    branches:
      - "master"
      - "rel/*"
jobs:
  exec:
    strategy:
      matrix:
        configuration.id: ["debug", "release"]
        rid.id: ["agnostic", "windows", "linux", "macos"]
        include:
          - configuration.id: "debug"
            configuration.name: "Debug"
            configuration.build.arguments: "--configuration Debug"
            configuration.test.arguments: "--configuration Debug"
            configuration.pack.arguments: "--configuration Debug"
            configuration.publish.arguments: "--configuration Debug"
          - configuration.id: "release"
            configuration.name: "Release"
            configuration.build.arguments: "--configuration Release"
            configuration.test.arguments: "--configuration Release"
            configuration.pack.arguments: "--configuration Release"
            configuration.publish.arguments: "--configuration Release"
          - rid.id: "agnostic"
            runs-on: "windows-latest"
            rid.publish.skip: ${{ true }}
          - rid.id: "windows"
            runs-on: "windows-latest"
            rid.name: "(Windows)"
            rid.skip: ${{ matrix['configuration.id'] == 'debug' }}
            rid.restore.arguments: "--runtime win10-x64"
            rid.build.arguments: "--runtime win10-x64"
            rid.test.arguments: "--runtime win10-x64 --collect \"Code Coverage\""
            rid.pack.skip: ${{ true }}
            rid.publish.arguments: "--runtime win10-x64"
          - rid.id: "linux"
            runs-on: "ubuntu-latest"
            rid.name: "(Linux)"
            rid.skip: ${{ matrix['configuration.id'] == 'debug' }}
            rid.restore.arguments: "--runtime linux-x64"
            rid.build.arguments: "--runtime linux-x64"
            rid.test.arguments: "--runtime linux-x64"
            rid.pack.skip: ${{ true }}
            rid.publish.arguments: "--runtime linux-x64"
          - rid.id: "macos"
            runs-on: "macos-latest"
            rid.name: "(macOS)"
            rid.skip: ${{ matrix['configuration.id'] == 'debug' }}
            rid.restore.arguments: "--runtime osx-x64"
            rid.build.arguments: "--runtime osx-x64"
            rid.test.arguments: "--runtime osx-x64"
            rid.pack.skip: ${{ true }}
            rid.publish.arguments: "--runtime osx-x64"
    name: ${{ matrix['configuration.name'] }} ${{ matrix['rid.name'] }}
    runs-on: ${{ matrix['runs-on'] }}
    defaults:
      run:
        shell: pwsh
    if: ${{ matrix['configuration.skip'] != 'true' && matrix['rid.skip'] != 'true' }}
    steps:
      - name: dotnet restore ${{ matrix['configuration.restore.arguments'] }} ${{ matrix['rid.restore.arguments'] }}
        continue-on-error: true
        if: ${{ matrix['configuration.restore.skip'] != 'true' && matrix['rid.restore.skip'] != 'true' }}
        run: dotnet restore ${{ matrix['configuration.restore.arguments'] }} ${{ matrix['rid.restore.arguments'] }}
      - name: dotnet build ${{ matrix['configuration.build.arguments'] }} ${{ matrix['rid.build.arguments'] }}
        if: ${{ matrix['configuration.build.skip'] != 'true' && matrix['rid.build.skip'] != 'true' }}
        run: dotnet build ${{ matrix['configuration.build.arguments'] }} ${{ matrix['rid.build.arguments'] }}
