name: .NET Continuous Integration

on:
  - pull_request
  - push

defaults:
  run:
    shell: pwsh

jobs:
  dotnet:
    strategy:
      matrix:
        configuration:
          - debug
          - release
        runtime:
          - agnostic
          - windows
          - linux
          - macos
        exclude:
          - configuration: debug
            runtime: windows
          - configuration: debug
            runtime: linux
          - configuration: debug
            runtime: macos
        include:
          - configuration: debug
            configuration.id: Debug
            configuration.display: Debug
          - configuration: release
            configuration.id: Release
            configuration.display: Release
          - runtime: agnostic
            os: windows-latest
          - runtime: windows
            os: windows-latest
            runtime.id: win10-x64
            runtime.display: (Windows, 64-bit)
          - runtime: linux
            os: ubuntu-latest
            runtime.id: linux-x64
            runtime.display: (Linux, 64-bit)
          - runtime: macos
            os: macos-latest
            runtime.id: osx-x64
            runtime.display: (macOS, 64-bit)
    name: ${{ matrix['configuration.display'] }} ${{ matrix['runtime.display'] }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Chekout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Prepare .NET SDK action
        uses: ./def/dotnet-sdk/prepare
      - name: .NET Version Information
        uses: ./def/dotnet-version-info
      - name: dotnet restore
        uses: ./def/dotnet-sdk
        with:
          command: restore
          project: |
            [Rr]ef/**/*.*proj
            [Ss]rc/**/*.*proj
            [Tt]ests?/**/*.*proj
            [Ss]amples?/**/*.*proj
          configuration: ${{ matrix['configuration.id'] }}
          runtime: ${{ matrix['runtime.id'] }}
      - name: dotnet build
        uses: ./def/dotnet-sdk
        with:
          command: build
          project: |
            [Rr]ef/**/*.*proj
            [Ss]rc/**/*.*proj
            [Tt]ests?/**/*.*proj
            [Ss]amples?/**/*.*proj
          configuration: ${{ matrix['configuration.id'] }}
          runtime: ${{ matrix['runtime.id'] }}
      - name: dotnet test (non-Windows OS)
        uses: ./def/dotnet-sdk
        if: ${{ runner.os != 'Windows' }}
        with:
          command: test
          project: |
            [Tt]ests?/**/*.*proj
          configuration: ${{ matrix['configuration.id'] }}
          runtime: ${{ matrix['runtime.id'] }}
      - name: dotnet test (Windows OS)
        uses: ./def/dotnet-sdk
        if: ${{ runner.os == 'Windows' }}
        with:
          command: test
          project: |
            [Tt]ests?/**/*.*proj
          configuration: ${{ matrix['configuration.id'] }}
          runtime: ${{ matrix['runtime.id'] }}
          dotnet-arguments: |
            --collect
            Code Coverage
      - name: dotnet pack
        uses: ./def/dotnet-sdk
        with:
          command: pack
          project: |
            [Ss]rc/**/*.*proj
          configuration: ${{ matrix['configuration.id'] }}
          runtime: ${{ matrix['runtime.id'] }}
