name: .NET Continuous Integration

on:
  pull_request: {}
  push:
    branches:
      - master
      - releases/**

defaults:
  run:
    shell: pwsh

jobs:
  dotnet:
    strategy:
      matrix:
        configuration:
          - debug
          - release
        runtime:
          - agnostic
          - windows
          - linux
          - macos
        targetFramework:
          - project
          - netstandard2.0
          - netstandard2.1
        excludes:
          - configuration: debug
            runtime: windows
          - configuration: debug
            runtime: linux
          - configuration: debug
            runtime: macos
          - configuration: debug
            targetFramework: netstandard2.0
          - configuration: debug
            targetFramework: netstandard2.1
        include:
          - configuration: debug
            configuration.display: Debug
          - configuration: release
            configuration.display: Release
          - runtime: agnostic
            os: windows-latest
          - runtime: windows
            os: windows-latest
            runtime.display: (Linux, 64-bit)
          - runtime: linux
            os: ubuntu-latest
            runtime.display: (Linux, 64-bit)
          - runtime: macos
            os: macos-latest
            runtime.display: (macOS, 64-bit)
          - targetFramework: netstandard2.0
            targetFramework.display: for .NET Standard 2.0
          - targetFramework: netstandard2.1
            targetFramework.display: for .NET Standard 2.1
    name: ${{ matrix['configuration.display'] }} ${{ matrix['runtime.display'] }} ${{ matrix['targetFramework.display'] }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Chekout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: .NET Version Information
        run: |
          dotnet --info
          dotnet msbuild -version
