name: GitHub Actions playground (using local repository references)
on:
  pull_request: {}
  push:
    branches:
      - "master"
      - "rel/*"
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      generated: ${{ steps.prepareDynamicJob.outputs.generated }}
    steps:
      - name: Checkout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v2
      - name: Prepare dynamically generated job
        id: prepareDynamicJob
        uses: ./bld/playground-prepare
  exec:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v2
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump needs context
        env:
          NEEDS_CONTEXT: ${{ toJson(needs) }}
        run: echo "$NEEDS_CONTEXT"
      - name: Import needs context
        id: prepare
        uses: ./bld/set-output-to-input
        with:
          value: ${{ needs.prepare.outputs.generated }}
      - name: Step 1
        uses: ${{ steps.prepare.outputs.value[1]['uses'] }}
        with: ${{ needs.prepare.outputs.value[1]['with'] }}
      - name: Step 2
        uses: ${{ needs.prepare.outputs.value[2]['uses'] }}
        with: ${{ needs.prepare.outputs.value[2]['with'] }}
